services:
# Main application service
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
  # Redis database service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  # Test service
  test:
    image: golang:1.19
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "test", "./...", "-v"]

networks:
  app-network:
    driver: bridge